#!/bin/bash

# Health Insights iOS App - Quick Setup Guide

echo "🏥 Health Insights iOS App Setup"
echo "================================"
echo ""
echo "📍 Project Location: /home/user/health/HealthInsights/"
echo ""
echo "All Swift source files are ready! You just need to create the Xcode project."
echo ""
echo "🔧 Option 1: Create Xcode Project (2 minutes)"
echo "----------------------------------------"
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. Choose: iOS → App"
echo "4. Settings:"
echo "   • Product Name: HealthInsights"
echo "   • Interface: SwiftUI"
echo "   • Language: Swift"
echo "   • Bundle ID: com.yourname.HealthInsights"
echo "5. Save to: /home/user/health/HealthInsights/"
echo "   ⚠️ IMPORTANT: Save INSIDE the existing HealthInsights folder"
echo "6. Delete the default ContentView.swift and HealthInsightsApp.swift"
echo "7. In Xcode, drag these folders into your project:"
echo "   • HealthInsights/Managers/"
echo "   • HealthInsights/Views/"
echo "   • HealthInsights/Assets.xcassets"
echo "8. Add these files:"
echo "   • HealthInsights/HealthInsightsApp.swift"
echo "   • HealthInsights/Info.plist"
echo "   • HealthInsights/HealthInsights.entitlements"
echo "9. In Project Settings → Signing & Capabilities:"
echo "   • Select your Team"
echo "   • Add '+Capability' → HealthKit"
echo "   • Enable Background Delivery"
echo "10. Set Deployment Target: iOS 16.0+"
echo "11. Build & Run! ⌘+R"
echo ""
echo "📦 Option 2: Use Swift Package (Alternative)"
echo "----------------------------------------"
echo "Run: cd /home/user/health/HealthInsights && swift package init --type executable"
echo "(Note: This creates a command-line tool, not an iOS app)"
echo ""
echo "📂 Your Files:"
ls -R /home/user/health/HealthInsights/HealthInsights/
echo ""
echo "💡 Tip: If you're on a Mac, you can open Xcode from Terminal:"
echo "   cd /home/user/health/HealthInsights"
echo "   open -a Xcode ."
echo ""
echo "Need help? Check the detailed README:"
echo "   cat /home/user/health/HealthInsights/README.md"
